// auth
const SIGN_IN = "SIGN_IN";
const SIGN_OUT = "SIGN_OUT";
const FETCH_USER = "FETCH_USER";

// socket
const GET_CHAT_HISTORY = "GET_CHAT_HISTORY";
const SEND_MSG = "SEND_MSG";
const JOIN_ROOM = "JOIN_ROOM";
const LEAVE_ROOM = "LEAVE_ROOM";

export { SIGN_IN, FETCH_USER, SIGN_OUT, GET_CHAT_HISTORY, SEND_MSG, JOIN_ROOM, LEAVE_ROOM };
